version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hotel_db_container
    # Настройки базы данных (должны совпадать с вашим .env)
    environment:
      #!!!!Не забыть поменять
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: hotel_db
    ports:
      - "5433:5432"
    # Сохраняем данные БД на жесткий диск, чтобы они не пропадали при перезапуске
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Healthcheck: проверка готовности базы принимать соединения
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hotel_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: hotel_app_container
    ports:
      - "8000:8000"
    # Пробрасываем переменные из нашего файла .env внутрь контейнера
    env_file:
      - .env
    # Монтируем текущую папку внутрь контейнера (нужно для hot-reload)
    volumes:
      - ./:/app
    # Ждем, пока БД не сообщит, что она "healthy" (здорова и готова)
    depends_on:
      db:
        condition: service_healthy
    # Переопределяем команду запуска, добавляя --reload для режима разработки
    command: >
      sh -c "sleep 5 && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

# Объявляем volume для БД
volumes:
  postgres_data: