"""Initial DB setup

Revision ID: e30432416976
Revises: 
Create Date: 2026-04-25 00:41:01.478925

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'e30432416976'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
